apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: inventory-database
    app.kubernetes.io/part-of: inventory-app
    app.openshift.io/runtime: postgresql
  name: inventory-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: inventory-database
      app.kubernetes.io/part-of: inventory-app
  strategy: {}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: inventory-database
        app.kubernetes.io/part-of: inventory-app
        name: inventory-database
    spec:
      containers:
        - image: quay.io/globex-recommendation/inventory-database:summit-connect
          imagePullPolicy: IfNotPresent
          name: inventory-database
          ports:
            - name: postgresql
              containerPort: 5432
              protocol: TCP
          resources: {}
          env:
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  key: database-user
                  name: inventory-database
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: database-password
                  name: inventory-database
            - name: POSTGRESQL_DATABASE
              valueFrom:
                secretKeyRef:
                  key: database-name
                  name: inventory-database
      serviceAccount: inventory-app
      serviceAccountName: inventory-app
