---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: inventory-database
    app.kubernetes.io/part-of: inventory-app
  name: inventory-database
spec:
  ports:
    - name: postgresql
      protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app.kubernetes.io/name: inventory-database
