apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: inventory-service
    app.kubernetes.io/part-of: inventory-app
    app.openshift.io/runtime: quarkus
  name: inventory-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: inventory-service
      app.kubernetes.io/part-of: inventory-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: inventory-service
        app.kubernetes.io/part-of: inventory-app
    spec:
      containers:
        - image: quay.io/globex-recommendation/inventory:summit-connect
          imagePullPolicy: IfNotPresent
          name: ionventory-service
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources: {}
          env:
            - name: QUARKUS_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  key: database-user
                  name: inventory-database
            - name: QUARKUS_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: database-password
                  name: inventory-database
            - name: POSTGRESQL_DATABASE
              valueFrom:
                secretKeyRef:
                  key: database-name
                  name: inventory-database
            - name: QUARKUS_DATASOURCE_JDBC_URL
              value: jdbc:postgresql://inventory-database:5432/${POSTGRESQL_DATABASE}
      serviceAccount: inventory-app
      serviceAccountName: inventory-app
